### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewModelKeyedFactory;

### ISSUE THREAD

**Issue by MaxFinit** [yoomoney/yookassa-android-sdk#100]
При старте токенизации

implementation fileTree(dir: "libs", include: ["*.aar"])
implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:6.4.5'

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewModelKeyedFactory;
        at ru.yoomoney.sdk.kassa.payments.di.n.a(Unknown Source:120)
        at ru.yoomoney.sdk.kassa.payments.paymentOptionList.m.onCreate(Unknown Source:8)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3009)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919)
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2825)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3048)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1786)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2832)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:417)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436)
        at android.app.Activity.performStart(Activity.java:8190)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3565)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8056)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.ClassNotFoundException: androidx.lifecycle.ViewModelKeyedFactory
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at ru.yoomoney.sdk.kassa.payments.di.n.a(Unknown Source:120) 
        at ru.yoomoney.sdk.kassa.payments.paymentOptionList.m.onCreate(Unknown Source:8) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3009) 
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919) 
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2825) 
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3048) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1786) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2832) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:417) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436) 
        at android.app.Activity.performStart(Activity.java:8190) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3565) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8056) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/ViewModelProvider$KeyedFactory;
        at ru.yoomoney.sdk.kassa.payments.di.n.a(Unknown Source:120) 
        at ru.yoomoney.sdk.kassa.payments.paymentOptionList.m.onCreate(Unknown Source:8) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:3009) 
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:474) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1780) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919) 
        at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2825) 
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3048) 
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:551) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261) 
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1862) 
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1786) 
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1723) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2919) 
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2832) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:417) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1436) 
        at android.app.Activity.performStart(Activity.java:8190) 
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3565) 
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221) 
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:236) 
        at android.app.ActivityThread.main(ActivityThread.java:8056) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.ViewModelProvider$KeyedFactory" on path: DexPathList[[zip file "/data/app/~~SPdbDZw1HxggFYFulRpXSA==/ru.kvartirka.android_new-c1Ep9Ndz_UCBRSeLlvChyg==/base.apk"],nativeLibraryDirectories=[/data/app/~~SPdbDZw1HxggFYFulRpXSA==/ru.kvartirka.android_new-c1Ep9Ndz_UCBRSeLlvChyg==/lib/arm64, /data/app/~~SPdbDZw1HxggFYFulRpXSA==/ru.kvartirka.android_new-c1Ep9Ndz_UCBRSeLlvChyg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 35 more
![image](https://user-images.githubusercontent.com/38804229/157458666-9f45b79e-a239-43b0-b708-c0c6f18ef49e.png)

**Comment by BulatMukhutdinov** [comment]
Получилось ли найти решение?

**Comment by BulatMukhutdinov** [comment]
Получилось ли найти решение?

**Comment by MaxFinit** [comment]
@BulatMukhutdinov 
> Получилось ли найти решение?

Откатил targetSdk до 30

**Comment by irininaelena** [comment]
Доброго времени суток. Попробуйте, пожалуйста, обновиться до версии 6.5.2
