### ISSUE TITLE
При значении настроек с Don't keep activities и открытой формой оплаты возникает сбой 

### ISSUE THREAD

**Issue by chim0380** [yoomoney/yookassa-android-sdk#18]
Время от времени в crashlytics  приходят сбои от моего приложения с ошибкой от формы оплаты Yandex (версия 1.3.0.6)

Fatal Exception: java.lang.IllegalStateException
Can not perform this action after onSaveInstanceState
android.support.v4.app.FragmentManagerImpl.checkStateLoss (FragmentManager.java:2080)
android.support.v4.app.DialogFragment.show (DialogFragment.java:144)
ru.yandex.money.android.sdk.Checkout.a (Unknown Source)
ru.yandex.money.android.sdk.Checkout$a.invoke (Unknown Source)

В поисках возможной причины предположил, что библиотека возможно сохраняет свое состояние, когда Activity уже в состоянии OnStop или ушло в Background. Путем имитации убийства Activity в тестовом приложении возникла KotlinNullPointerException. Возможно эти ошибки связаны. 

**Как повторить ошибку KotlinNullPointerException**
В Developer Options указать значение Don't keep activities и Background process limit отличное от Standart и выполнить следующие действия:
1. Открыть диалог оплаты 
2. Нажать на кнопку Домой телефона
3. Запустить приложение из  "Recent Apps"

 то возникает FATAL EXCEPTION: main
    Process: com.example.vladimir.yandexmoneytestapplication, PID: 29882
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.vladimir.yandexmoneytestapplication/com.example.vladimir.yandexmoneytestapplication.MainActivity}: kotlin.KotlinNullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: kotlin.KotlinNullPointerException
        at ru.yandex.money.android.sdk.impl.j.l.onCreate(Unknown Source:30)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)

![untitled3](https://user-images.githubusercontent.com/13486110/50893210-6dc2e700-1411-11e9-82c2-f375229205ad.gif)

**Comment by drukarev** [comment]
Спасибо, поправим в ближайшей версии.

**Comment by Winner28** [comment]
Здравствуйте, подскажите, проблема воспроизводится?

**Comment by iskandarshabaev** [comment]
Кажется что такой проблемы больше нет в новых версиях. Просьба снова открыть issue, она появится.
