### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by vsevolod-sp** [yoomoney/yookassa-android-sdk#40]
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:793)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:791)
	at ru.yandex.money.android.sdk.impl.d$ag.invoke()
	at ru.yandex.money.android.sdk.a.l$a.invoke()
	at ru.yandex.money.android.sdk.a.e.run()
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
```

**Comment by vsevolod-sp** [comment]
[crash_11020540276494384101_6.4.0.txt](https://github.com/yandex-money/yandex-checkout-android-sdk/files/4114150/crash_11020540276494384101_6.4.0.txt)

Решили нет проблему? После совершения платежа вылетает приложение (у некоторых пользователей), но пдатеж проходит успешно.

**Comment by ShadowLightMan** [comment]
@vsevolod-sp пока не решили они

**Comment by Winner28** [comment]
Дубликат https://github.com/yoomoney/yookassa-android-sdk/issues/49
