### ISSUE TITLE
Ошибка logo must not be null

### ISSUE THREAD

**Issue by chim0380** [yoomoney/yookassa-android-sdk#48]
При вызове sdk на некоторых старых версиях (например 4.2, 4.4) возникают сбой с ошибкой
**logo must not be null**

**Comment by Winner28** [comment]
Здравствуйте, можете приложить подробный stack trace ошибки?

**Comment by chim0380** [comment]
Android 4.4.2, Телефон Blade C340
 Android 4.4.4, ТелефонGalaxy S4 Mini

Fatal Exception: java.lang.IllegalStateException: logo must not be null
       at ru.yandex.money.android.sdk.impl.h.m$f.invoke(m.java)
       at ru.yandex.money.android.sdk.a.a$aa.invoke(a.java)
       at ru.yandex.money.android.sdk.impl.b.run(b.java)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:932)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:748)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by Winner28** [comment]
Здравствуйте, подскажите, на девайсах с Android 5+ проблема воспроизводится?

**Comment by iskandarshabaev** [comment]
Работа с logo в библиотеке обновилась, более того подняли минимальную версию до API 21
Просьба переоткрыть issue, в случае воспроизведения на версиях android 5+
