### ISSUE TITLE
Fatal Exception: java.util.ConcurrentModificationException приложение падает из-за либы

### ISSUE THREAD

**Issue by AdislanSaidov** [yoomoney/yookassa-android-sdk#49]
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:757)
       at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
       at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:788)
       at ru.yandex.money.android.sdk.impl.d$ag.invoke(d.java:35)
       at ru.yandex.money.android.sdk.a.l$a.invoke(l.java:37)
       at ru.yandex.money.android.sdk.a.e.run(e.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by ShadowLightMan** [comment]
репорт из crashlytics
Устройство
Марка: samsung
Модель: Galaxy A30
Ориентация: Вертикальная
Свободная оперативная память: 671.05 MB
Свободное место на диске: 1.63 GB
Операционная система
Версия: 10
Ориентация: Вертикальная
Root-доступ: Нет
Сбой
Дата: 2 апр. 2020 г., 13:45:11
Версия приложения: 1.0.0 (26)

**Comment by ShadowLightMan** [comment]
репорт из crashlytics
Устройство
Марка: samsung
Модель: Galaxy A30
Ориентация: Вертикальная
Свободная оперативная память: 671.05 MB
Свободное место на диске: 1.63 GB
Операционная система
Версия: 10
Ориентация: Вертикальная
Root-доступ: Нет

**Comment by Winner28** [comment]
Здравствуйте, подскажите, проблема актуальна на новых версиях библиотеки?

**Comment by AdislanSaidov** [comment]
> Здравствуйте, подскажите, проблема актуальна на новых версиях библиотеки?

Добрый день! Пока не замечал
