### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to resume activity {ru.shopdobro.app/ru.yandex.money.android.sdk.impl.CheckoutActivity}: kotlin.UninitializedPropertyAccessException: lateinit property sessionReporter has not been initialized

### ISSUE THREAD

**Issue by AdislanSaidov** [yoomoney/yookassa-android-sdk#51]
Caused by kotlin.UninitializedPropertyAccessException: lateinit property sessionReporter has not been initialized
       at ru.yandex.money.android.sdk.impl.d.a(d.java:6)
       at ru.yandex.money.android.sdk.impl.n.onResume(n.java:5)
       at androidx.fragment.app.Fragment.performResume(Fragment.java:17)
       at androidx.fragment.app.FragmentStateManager.resume(FragmentStateManager.java:30)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:249)
       at androidx.fragment.app.FragmentManager.f(FragmentManager.java:2)
       at androidx.fragment.app.FragmentManager.g(FragmentManager.java:55)
       at androidx.fragment.app.FragmentManager.a(FragmentManager.java:47)
       at androidx.fragment.app.FragmentManager.d(FragmentManager.java:9)
       at androidx.fragment.app.FragmentManager.m(FragmentManager.java:6)
       at androidx.fragment.app.FragmentActivity.onPostResume(FragmentActivity.java:16)
       at androidx.appcompat.app.AppCompatActivity.onPostResume(AppCompatActivity.java)
       at android.app.Activity.performResume(Activity.java:7597)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4006)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4046)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

Устройство
Марка: samsung
Модель: Galaxy S8
Ориентация: Вертикальная
Свободная оперативная память: 923.87 MB
Свободное место на диске: 7.24 GB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой

Почему-то ваша библиотека сбоит у некоторых моих юзеров

**Comment by Winner28** [comment]
Спасибо, приняли во внимание.

**Comment by AdislanSaidov** [comment]
Устройство
Марка: Xiaomi
Модель: Redmi Note 7
Ориентация: Вертикальная
Свободная оперативная память: 696.75 MB
Свободное место на диске: 491.61 MB
Операционная система
Версия: 9
Ориентация: Вертикальная
Root-доступ: Нет
Сбой

**Comment by Winner28** [comment]
Дубликат:
https://github.com/yoomoney/yookassa-android-sdk/issues/42
