### ISSUE TITLE
Fatal Exception: java.lang.ClassCastException

### ISSUE THREAD

**Issue by chim0380** [yoomoney/yookassa-android-sdk#53]
Марка: Xiaomi, Модель: MI 8 SE,Версия: 8.1.0
Марка: samsung,Модель: Galaxy A6+,Версия: 9
Марка: samsung,Модель: Galaxy A51,Версия: 10
Марка: HUAWEI,Модель: Honor 7C,Версия: 8.0.0

**Сбой**
Fatal Exception: java.lang.ClassCastException: ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.n
       at ru.yandex.money.android.sdk.impl.n$g.invoke(n.java)
       at ru.yandex.money.android.sdk.a.a$aa.invoke(a.java:13)
       at ru.yandex.money.android.sdk.impl.b.run(b.java:2)
       at android.os.Handler.handleCallback(Handler.java:2)
       at android.os.Handler.dispatchMessage(Handler.java:4)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:65)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:11)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:345)

**Comment by andrshab** [comment]
Та же ошибка на DEXP GS150. Android 8.1.0

**Comment by nbnbbs** [comment]
`D/Yandex.Checkout.SDK: Load payment option list: viewModel: PaymentOptionListSuccessViewModel(paymentOptions=[PaymentOptionListItemViewModel(optionId=2, icon=android.graphics.drawable.VectorDrawable@bc642f7, title=Bank card, additionalInfo=null, canLogout=false)], showLogo=false)
D/Yandex.Checkout.SDK: Select payment option: invoke with 2
D/Yandex.Checkout.SDK: Select payment option: progress: ru.yandex.money.android.sdk.impl.contract.j@9cfe6e3
D/AndroidRuntime: Shutting down VM

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mylittlepony.rainbowcatcher, PID: 20274
    java.lang.ClassCastException: ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.j
        at ru.yandex.money.android.sdk.impl.contract.f$g.invoke(Unknown Source:0)
        at ru.yandex.money.android.sdk.a.a$aa.invoke(Unknown Source:13)
        at ru.yandex.money.android.sdk.impl.b.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

D/Yandex.Checkout.SDK: Select payment option: output: SelectedPaymentOptionOutputModel(paymentOption=NewCard(id=2, charge=Amount(value=599.00, currency=RUB), fee=null, savePaymentMethodAllowed=true), hasAnotherOptions=false, walletLinkingPossible=false)
D/Yandex.Checkout.SDK: Select payment option: viewModel: ContractSuccessViewModel(shopTitle=Blue Pony, shopSubtitle=Subtitle, paymentOption=PaymentOptionViewModel(optionId=2, icon=android.graphics.drawable.VectorDrawable@7fc2fc9, name=Bank card, amount=599.00 ₽, additionalInfo=null, canLogout=false, fee=null), licenseAgreement=By clicking this button, you accept terms and conditions of the service, showChangeButton=false, savePaymentMethodViewModel=ru.yandex.money.android.sdk.impl.contract.y$c@7c22041, showAllowWalletLinking=false, paymentAuth=null, showPhoneInput=false, googlePayContractViewModel=null)`
Поймал на эмуляторе android 26 апи

**Comment by KirillArtemenko** [comment]
Xiaomi Redmi 5 Plus Android 8.1.0

```
Fatal Exception: java.lang.ClassCastException: ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.j
       at ru.yandex.money.android.sdk.impl.contract.f$g.invoke()
       at ru.yandex.money.android.sdk.a.a$aa.invoke(:13)
       at ru.yandex.money.android.sdk.impl.b.run(:2)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6651)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

**Comment by iskandarshabaev** [comment]
Обновили библиотеку, проблема должна пропасть в версии 5.1.0
Просьба при повторном воспроизведении переоткрыть issue
