### ISSUE TITLE
Различные сбои

### ISSUE THREAD

**Issue by username4564** [yoomoney/yookassa-android-sdk#55]
Сбои собранные из crashlytics. Версия библиотеки 3.0.3

Fatal Exception: java.lang.ClassCastException: ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.n
       at ru.yandex.money.android.sdk.impl.n$g.invoke(n.java)
       at ru.yandex.money.android.sdk.a.a$aa.invoke(a.java:27)
       at ru.yandex.money.android.sdk.impl.b.run(b.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8125)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

samsung Galaxy S9 Android 10
HUAWEI honor 10 Lite Android 10
HUAWEI Honor 7A Android 8.1.0
HUAWEI HONOR 20 PRO Android 9
samsung Galaxy A5(2017) 8.0.0
samsung Galaxy S8+ 9
Xiaomi MI 8 Lite Android 9
Xiaomi Redmi 6 Pro Android 9
И еще много других девайсов.

Fatal Exception: java.lang.ClassCastException: ru.yandex.money.android.sdk.impl.h.t cannot be cast to ru.yandex.money.android.sdk.impl.contract.j
       at ru.yandex.money.android.sdk.impl.contract.f$g.invoke(f.java)
       at ru.yandex.money.android.sdk.a.a$aa.invoke(a.java:27)
       at ru.yandex.money.android.sdk.impl.b.run(b.java:2)
       at android.os.Handler.handleCallback(Handler.java:794)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:6662)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

Xiaomi Redmi 6A Android 8.1.0
HUAWEI Honor 6A Android 7.0
samsung Galaxy J8 Android 9
UMIDIGI A5 Pro Android 9
HUAWEI HUAWEI P smart Z Android 10
HUAWEI Honor 9 Lite Android 9
И еще много других девайсов.

Fatal Exception: java.lang.IllegalStateException: rootContainer must not be null
       at ru.yandex.money.android.sdk.impl.contract.f$g.invoke(f.java:27)
       at ru.yandex.money.android.sdk.a.a$aa.invoke(a.java:27)
       at ru.yandex.money.android.sdk.impl.b.run(b.java:2)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

HUAWEI Honor 9 Lite Android 9
Xiaomi Redmi Note 7 Android  9
HUAWEI Honor 9 Lite Android 9
Prestigio PSP5545DUO Android 8.1.0

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=109341, result=-1, data=Intent { (has extras) }} to activity {*.*.*/ru.yandex.money.android.sdk.impl.CheckoutActivity}: java.lang.IllegalStateException: Required value was null.
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by java.lang.IllegalStateException: Required value was null.
       at ru.yandex.money.android.sdk.impl.contract.f.onActivityResult(f.java:17)
       at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
       at android.app.Activity.dispatchActivityResult(Activity.java:7797)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

HUAWEI HUAWEI Y6s Android 9
HUAWEI Honor 9 Lite Android 9

Fatal Exception: java.lang.IllegalStateException: Fragment a$c{d3004fc (2428f980-7f65-4b71-a17b-ecfe8f43e2fb)} has not been attached yet.
       at androidx.fragment.app.Fragment.getChildFragmentManager(Fragment.java:923)
       at ru.yandex.money.android.sdk.impl.e.a.b.b(b.java:9)
       at ru.yandex.money.android.sdk.impl.e.a.b$c.invoke(b.java:9)
       at ru.yandex.money.android.sdk.a.a$r.invoke(a.java:4)
       at ru.yandex.money.android.sdk.impl.b.run(b.java:2)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7814)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1047)

samsung Galaxy A71 Android 10
samsung Galaxy Note8 9

**Comment by iskandarshabaev** [comment]
Обновили библиотеку, проблема должна пропасть в версии 5.1.0
Просьба при повторном воспроизведении переоткрыть issue
