### ISSUE TITLE
Не отображаются способы оплаты

### ISSUE THREAD

**Issue by vsevolod-sp** [yoomoney/yookassa-android-sdk#71]
Код вызова формы:

```
UiParameters uiParameters = new UiParameters(false, new ColorScheme(config.getAttributeColor(R.attr.colorAccent)));
TestParameters testParameters = new TestParameters(true, false, null);

Set<PaymentMethodType> paymentMethodTypes = new HashSet<>();
            paymentMethodTypes.add(PaymentMethodType.YOO_MONEY);
            paymentMethodTypes.add(PaymentMethodType.BANK_CARD);
            paymentMethodTypes.add(PaymentMethodType.SBERBANK);

            PaymentParameters paymentParameters = new PaymentParameters(
                    new Amount(new BigDecimal(pagePromo.getMethods().get(pos).getPrice()), Currency.getInstance("RUB")),
                    pagePromo.getMethods().get(pos).getTitle(),
                    pagePromo.getMethods().get(pos).getDescription(),
                    Config.YC_CLI_KEY,
                    Config.YC_SHOP_ID,
                    SavePaymentMethod.ON,
                    paymentMethodTypes
            );

            Intent i = Checkout.createTokenizeIntent(this, paymentParameters, testParameters, uiParameters);
            startActivityForResult(i, REQUEST_CODE_TOKENIZE);
```

В логах заметил ошибки:

```
D/YooKassa.SDK: Load payment option list: error: null
    a.a.a.a.a.e.g.f
        at a.a.a.a.a.e.g.b.a(:17)
        at a.a.a.a.a.e.g.b.invoke(Unknown Source:2)
        at a.a.a.a.a.a.s0.i0.invoke(Unknown Source:2)
        at a.a.a.a.a.d.k$b.invoke(:7)
        at a.a.a.a.a.d.c.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

`D/YooKassa.SDK: Load payment option list: viewModel: PaymentOptionListFailViewModel(error=Нет доступных способов оплаты, showLogo=false)`

**Comment by iskandarshabaev** [comment]
Здравствуйте.
Напишите пожалуйста нам на почту с этой проблемой, поможем оперативно разобраться b2b_support@yoomoney.ru
