### ISSUE TITLE
Падение при попытке оплаты Didn't find class "ru.yoomoney.sdk.tmx.TmxProfiler"

### ISSUE THREAD

**Issue by RJSDevel** [yoomoney/yookassa-android-sdk#94]
implementation 'ru.yoomoney.sdk.kassa.payments:yookassa-android-sdk:6.4.1'
android.enableR8 = true

После ввода карты:
    java.lang.NoClassDefFoundError: Failed resolution of: Lru/yoomoney/sdk/tmx/TmxProfiler;
        at ru.yoomoney.sdk.kassa.payments.di.i.get(Unknown Source:2)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at ru.yoomoney.sdk.kassa.payments.contract.di.m.get(Unknown Source:1)
        at ru.yoomoney.sdk.kassa.payments.tokenize.di.g.get(Unknown Source:1)
        at ru.yoomoney.sdk.kassa.payments.tokenize.di.h.get(Unknown Source:1)
        at androidx.lifecycle.ViewModelKeyedFactory.create(Unknown Source:20)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at ru.yoomoney.sdk.kassa.payments.tokenize.w$a.invoke(Unknown Source:1)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at ru.yoomoney.sdk.kassa.payments.tokenize.w.b(Unknown Source:2)
        at ru.yoomoney.sdk.kassa.payments.tokenize.w.onViewCreated(Unknown Source:26)
        at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:8035)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by RJSDevel** [comment]
ThreatMetrix Android SDK 5.4-73.aar в папке libs
