### ISSUE TITLE
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent

### ISSUE THREAD

**Issue by Extro5** [yoomoney/yookassa-android-sdk#96]
java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
      
https://developer.android.com/guide/components/intents-filters#DeclareMutabilityPendingIntent

**Comment by iskandarshabaev** [comment]
Подскажите, пожалуйста, версию targetSdk, compileSdkVersion и версию библиотеки которую используете

**Comment by Extro5** [comment]
@iskandarshabaev 
targetSdkVersion = 31
compileSdkVersion=31
версия библиотеки: 6.4.4

**Comment by iskandarshabaev** [comment]
- В какой момент происходит ошибка?
- Только на android 12?

**Comment by Extro5** [comment]
@iskandarshabaev 
1. При запуске приложения.
2. У нас воспроизводится только на 12 андроиде. (На 10ке все норм).

**Comment by SNechaev1** [comment]
таже ошибка на андроиде 12, исправьте уже, висит с ноября
targetSdkVersion = 31
compileSdkVersion=31
версия библиотеки: 6.4.5

**Comment by irininaelena** [comment]
Доброго времени суток! Прошу прощения за долгий ответ. Добавьте, пожалуйста, к себе зависимость implementation 'androidx.work:work-runtime:2.7.1' в build.gradle, приложение должно перестать падать
